// The Swift Programming Language
// https://docs.swift.org/swift-book

// sample OptCode for the VM, suppose it should be generated by the lexer.
let program: [UInt8] = [
    OptCode.pushi.rawValue, 24,
    OptCode.pushi.rawValue, 8,
    OptCode.minus.rawValue,
    OptCode.pushi.rawValue, 16,
    OptCode.add.rawValue,
    OptCode.print.rawValue,
    OptCode.halt.rawValue,
]

// Initialize and execute
let vm = VirtualMachine(byteCode: program)
vm.run()
